WIP: Cerchie/add patch
confluentinc/ide-sidecar pull request #264
Opened 2024-12-26 18:03 UTC by Cerchie

## Summary of Changes

Status: DRAFT. Using this PR to support conversations and self-review. 

## Any additional details or context that should be provided?

## Pull request checklist

Please check if your PR fulfills the following (if applicable):

- Tests:
    - [ ] Added new
    - [ ] Updated existing
    - [ ] Deleted existing
- [ ] Have you validated this change locally against a running instance of the Quarkus dev server?
    ```shell
    make quarkus-dev
    ```
- [ ] Have you validated this change against a locally running native executable?
    ```shell
    make mvn-package-native && ./target/ide-sidecar-*-runner
    ```

2025-01-06 15:35 UTC, flippingbits reviewed
Thanks, @Cerchie! I have a few questions.

2025-01-06 16:00 UTC, Cerchie commented on src/main/java/io/confluent/idesidecar/restapi/resources/ConnectionsResource.java
> +          description = "Could not authenticate with connection configuration updated with PATCH",
oh good catch, updating both messages

2025-01-06 16:05 UTC, Cerchie commented on src/main/java/io/confluent/idesidecar/restapi/connections/ConnectionStateManager.java
> +        .item(() -> mergedSpec.validateUpdate(newSpec))
that makes sense. I left in the logic to check that the type is the same but did not make it a required field.

2025-01-06 16:08 UTC, Cerchie commented on src/main/java/io/confluent/idesidecar/restapi/connections/ConnectionStateManager.java
> +        .item(() -> mergedSpec.validateUpdate(newSpec))
oh hold on, this method also eventually gets called when a PUT request is made... I'll need to update the logic differently because we do want those to be required with a PUT request

2025-01-06 16:12 UTC, Cerchie commented on src/main/java/io/confluent/idesidecar/restapi/connections/ConnectionStateManager.java
> +
thank you!

2025-01-06 16:32 UTC, Cerchie commented on src/main/java/io/confluent/idesidecar/restapi/connections/ConnectionStateManager.java
> +          return Uni.createFrom().voidItem();
I suppose this would make for easier extension of the functionality...  I'll give it a try

2025-01-06 16:33 UTC, Cerchie commented on src/main/java/io/confluent/idesidecar/restapi/connections/ConnectionStateManager.java
> +          // No need to validate the spec for LOCAL, DIRECT, and PLATFORM connections
if is fine! it does inflate the lines of code a bit and doesn't add much to the readability IMO, but I changed it, lmk what you think

2025-01-06 21:30 UTC, rohitsanj requested changes
@Cerchie I'm not sure that we want to implement the PATCH route this way (by merging a provided spec with an existing spec). The linked issue https://github.com/confluentinc/ide-sidecar/issues/168 recommends using JSON-patch since it is likely supported out-of-the-box by Quarkus. 

This way, we can have a [standardized](https://datatracker.ietf.org/doc/html/rfc6902/) protocol for patching changes to JSON objects, without having to refactor the implementation when a field is removed or added.

2025-01-07 21:55 UTC, rohitsanj commented on src/main/java/io/confluent/idesidecar/restapi/resources/ConnectionsResource.java
> +  private static final Logger logger = LoggerFactory.getLogger(ConnectionsResource.class);
Let's import `import io.quarkus.logging.Log` and then directly use it with `Log.<whatever>`. Refer to other code files for similar usage.

2025-01-07 21:56 UTC, rohitsanj commented on src/main/java/io/confluent/idesidecar/restapi/models/ConnectionSpec.java
> +    if (!Objects.equals(newSpec.type, type)) {
Was this another change leftover from the previous implementation? Ideally we still want to check if the new spec declares type as null.

2025-01-07 22:05 UTC, Cerchie commented on src/main/java/io/confluent/idesidecar/restapi/models/ConnectionSpec.java
> +    if (!Objects.equals(newSpec.type, type)) {
I'm checking in the method itself now... thoughts on that?

2025-01-07 22:45 UTC, rohitsanj requested changes
Few minor comments

2025-01-08 14:29 UTC, Cerchie commented on src/main/java/io/confluent/idesidecar/restapi/resources/ConnectionsResource.java
> +        description = "Could not authenticate with provided API token",
Since there's [conflicting feedback ](https://github.com/confluentinc/ide-sidecar/pull/264#discussion_r1904242108)on this, I gave the endpoint a try and it seems that this description is correct:

```
❯ curl -s -X PATCH -d'{"id": "c1", "name": "DTX-test", "type": "CCLOUD"}' -H "Authorization: Bearer NONE" -H "Content-Type:application/json" http://localhost:26636/gateway/v1/connections/c1 | jq -r .
{
  "status": "401",
  "code": "unauthorized",
  "title": "Unauthorized",
  "id": "521c100f-d380-4be3-ac34-ed83a2f4a6d2",
  "errors": [
    {
      "code": "unauthorized",
      "title": "Unauthorized",
      "detail": "Refresh token is missing."
    }
  ]
}
```

and
```
❯ curl -s -X PATCH -d'{"id": "c1", "name": "DTX-test", "type": "CCLOUD"}'  -H "Content-Type:application/json" http://localhost:26636/gateway/v1/connections/c1 | jq -r .
{
  "status": "401",
  "code": "unauthorized",
  "title": "Unauthorized",
  "id": "4bd256b2-972e-46de-9dda-6a021aa20505",
  "errors": [
    {
      "code": "unauthorized",
      "title": "Unauthorized",
      "detail": "Refresh token is missing."
    }
  ]
}
```

2025-01-08 14:33 UTC, flippingbits commented on src/main/java/io/confluent/idesidecar/restapi/resources/ConnectionsResource.java
> +        description = "Could not authenticate with provided API token",
I think the `@APIResponse` annotation is affecting only the OpenAPI spec not the actual API responses.

2025-01-08 15:07 UTC, Cerchie commented on src/main/java/io/confluent/idesidecar/restapi/models/ConnectionSpec.java
> +    if (!Objects.equals(newSpec.type, type)) {
We'd need to change the method signature on `validateUpdate` to track whether it's a PUT or PATCH, which I've put back in the code. This is because we don't need 'name' with a PATCH if a user doesn't want to PATCH that field, but PUT requires the whole thing. Setting it as null is something we probably don't want for either, so I also updated the logic.

2025-01-10 10:57 UTC, flippingbits reviewed
Great progress, @Cerchie! I have a few more minor comments.

2025-01-10 10:57 UTC, flippingbits commented on src/main/java/io/confluent/idesidecar/restapi/resources/ConnectionsResource.java
> +        }
The indentation looks a bit off. I hope I got it right.

```suggestion
    try {
      JsonNode existingSpecNode = mapper.valueToTree(
          connectionStateManager.getConnectionState(id).getSpec()
      );

      JsonNode patchedSpecNode = patch.apply(existingSpecNode);
      ConnectionSpec patchedSpec = mapper.treeToValue(patchedSpecNode, ConnectionSpec.class);
      return connectionStateManager
          .updateSpecForConnectionState(id, patchedSpec)
          .chain(ignored -> Uni.createFrom().item(() -> getConnectionModel(id)));
    } catch (JsonPatchException | IOException e) {
      Log.errorf("Failed to patch connection with ID=%s: %s", id, e.getMessage());
      return Uni.createFrom().nullItem();
    }
  }
```

2025-01-10 10:57 UTC, flippingbits commented on src/main/java/io/confluent/idesidecar/restapi/resources/ConnectionsResource.java
> +            return Uni.createFrom().nullItem();
From reading, it seems this returns an empty payload with the status 200.

Should this return a 4xx status with error messages in the payload instead?

2025-01-10 10:57 UTC, flippingbits commented on src/test/java/io/confluent/idesidecar/restapi/resources/ConnectionsResourceTest.java
> +        requestType == null ? "null" : "\"" + requestType + "\"");
Glad we're using `JsonMergePatch` not `JsonPatch` :)

2025-01-10 10:57 UTC, flippingbits commented on src/test/java/io/confluent/idesidecar/restapi/resources/ConnectionsResourceTest.java
> +        requestType == null ? "null" : "\"" + requestType + "\"");
What about submitting "partial updates", which don't hold the keys that should not be changed, to the `PATCH` endpoint? For instance, if we want to test updating the connection type, we should use a payload that looks like `{ "type": "NEW_TYPE" }` not `{ "id": "CURRENT_ID", "name": "CURRENT_NAME", "type": "NEW_TYPE" }`. Otherwise, we'd test the same request payloads as used for the `PUT` endpoint. WDYT?

You can easily create such payloads with the `ConnectionSpec` record so you don't have to build them from scratch yourself:

```suggestion
    var payload = new ConnectionSpec(
        requestId,
        requestName,
        requestType != null ? ConnectionType.valueOf(requestType) : null
    );
    var mapper = new ObjectMapper();
    var patchRequest = mapper.writeValueAsString(payload);
```

2025-01-10 16:01 UTC, Cerchie commented on src/test/java/io/confluent/idesidecar/restapi/resources/ConnectionsResourceTest.java
> +        requestType == null ? "null" : "\"" + requestType + "\"");
thank you! I've updated the tests

2025-01-10 18:32 UTC, rohitsanj submitted a review, later dismissed
@Cerchie I think the tests are shaping up well, I just have a few minor comments. I see from the coverage report that the patch endpoint is not covered, could you please look why this is?

2025-01-10 18:33 UTC, rohitsanj commented on src/test/java/io/confluent/idesidecar/restapi/resources/ConnectionsResourceTest.java
> +      String testName,
Sorry, missed this in my earlier review: Let's keep the PUT tests as is and create new ones for PATCH.

2025-01-10 20:34 UTC, Cerchie commented on src/test/java/io/confluent/idesidecar/restapi/resources/ConnectionsResourceTest.java
> +      String testName,
eek! didn't realize I removed this. thanks for catching

2025-01-13 08:03 UTC, flippingbits reviewed
Thanks for the updates, @Cerchie! I feel you're very close to merging this PR into the `main` branch. I have a few more minor comments. Also, can you add negative test cases for the `PATCH` endpoint so that we verify the behavior in case of errors? Otherwise, your PR looks good to me!

2025-01-13 08:03 UTC, flippingbits commented on src/test/java/io/confluent/idesidecar/restapi/resources/ConnectionsResourceTest.java
> +      if (testName.contains("Change Type")) {
This way we don't have to rely on the `testName` for determining if the test case updates the connection type:

```suggestion
    var connectionSpec = connectionStateManager.getConnectionSpec("c1");
    var testUpdatesConnectionType = !connectionSpec.type().equals(
        ConnectionType.valueOf(requestType));

    var testContext = new VertxTestContext();
    refreshConnectionStatusAndThen(connectionId, testContext, () -> {
      assertAuthStatus(connectionId, "VALID_TOKEN");

      // Log current state if testing type change
      if (testUpdatesConnectionType) {
```

2025-01-13 17:04 UTC, flippingbits submitted a review, later dismissed
I have two more very minor questions/suggestions. Otherwise, this PR looks good to me. Excellent work, @Cerchie 🎉 

@rohitsanj Do you want to take another look before we merge it since you reviewed earlier revisions of this PR?

2025-01-14 07:35 UTC, flippingbits reviewed
Thanks for the update, @Cerchie! I have one more question before we merge it into `main`.

2025-01-14 07:35 UTC, flippingbits commented on src/main/java/io/confluent/idesidecar/restapi/resources/ConnectionsResource.java
> +        }
Do you mind reformatting this code and updating the formatted string in line 199? I think using `{}` as placeholders won't work.

```suggestion
    try {
      JsonNode existingSpecNode = mapper.valueToTree(
          connectionStateManager.getConnectionState(id).getSpec());

      JsonNode patchedSpecNode = patch.apply(existingSpecNode);
      ConnectionSpec patchedSpec = mapper.treeToValue(patchedSpecNode, ConnectionSpec.class);
      return connectionStateManager
          .updateSpecForConnectionState(id, patchedSpec)
          .chain(ignored -> Uni.createFrom().item(() -> getConnectionModel(id)));
    } catch (JsonPatchException | IOException e) {
      Log.errorf(
          "Failed to patch connection: %s, Connection ID: %s, Request: %s",
          e.getMessage(),
          id,
          patch
      );
      throw new WebApplicationException(
          "Failed to patch connection, please check the format of your request",
          Response.Status.BAD_REQUEST
      );
    }
  }
```

2025-01-14 21:07 UTC, flippingbits commented on src/main/java/io/confluent/idesidecar/restapi/resources/ConnectionsResource.java
> +        }
Thanks!

2025-01-14 21:08 UTC, flippingbits approved these changes
LGTM. Thank you, @Cerchie!

2025-01-14 21:50 UTC, merged